# Generated by Django 2.2 on 2019-04-06 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Наименование изображения')),
                ('date_created', models.DateTimeField(verbose_name='Дата загрузки изображения')),
                ('photo', models.ImageField(upload_to='upload_images')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Post', verbose_name='Пост')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь/Автор')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Наименование файла')),
                ('date_created', models.DateTimeField(verbose_name='Дата загрузки файла')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Post', verbose_name='Пост')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь/Автор')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
