# Generated by Django 2.2 on 2019-04-06 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_document_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='upload_documents'),
            preserve_default=False,
        ),
    ]
